name: Angular CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Você pode ajustar para a versão Node.js que o Angular requer
    - run: npm install  # Instala as dependências do Angular
    - run: npm run build -- --prod  # Cria o build de produção do Angular
    - run: npm test  # Executa os testes unitários